---
title: "Untitled"
author: "Matthew Upson"
date: "24/12/2014"
output: html_document
---

```{r}

require(dplyr)
require(magrittr)
require(tidyr)
require(lubridate)
require(ggplot2)
require(ggmap)

source("facet_wrap_labeller.R")

```

```{r}

SensorPiB_sql <- src_sqlite("~/Dropbox/Apps/SensorPi/SensorPiB.db")

SensorPiB <- tbl(
  SensorPiB_sql,
  sql("select * from SensorPiB where timestamp > '2014-12-24'")
  ) %>% collect

p <- SensorPiB %>% 
  dplyr::mutate(
    timestamp = ymd_hms(timestamp), 
    light = log(light)*-1
    ) %>% 
  gather(
    variable, 
    value, 
    temp1:humidity
    ) %>% 
  dplyr::mutate(
    variable1 = ifelse(grepl("temp",variable),"temp",variable)
    ) %>%
  ggplot(
    aes(
      x = timestamp, 
      y = value, 
      colour = variable 
      )
    )+
  geom_path()+
  facet_wrap(
    ~variable1,
    scales = "free",
    ncol = 1)+
  theme(
    legend.position = "right"
    ) +
  scale_colour_discrete(
    labels = c(
      "Internal temperature",
      "External temperature",
      "Internal temperature 2",
      "Light (relative values)",
      "Relative humidity"
      )
    )+
  xlab(
    "Timestamp"
    )

facet_labels <- c(
  expression(Light~(relative~values)),
  expression(Internal~relative~humidity~(percent)),
  expression(Temperature~(~degree~C))  
  )
  
p1 <- facet_wrap_labeller(
  p,
  facet_labels
  )


pdf("sensorpib.pdf",width=8,height=10)
p1
dev.off()
```


```{r}

Log_sql <- src_sqlite("~/Dropbox/Apps/SensorPi/Log.db")

Log <- tbl(
  Log_sql,sql(
    "select * from temp where timsetamp > '2014-12-24'")
  ) %>% 
  collect


p <- Log %>% 
  dplyr::mutate(
    timestamp = ymd_hms(timsetamp),
    light = log(light)*-1
    ) %>% 
  gather(
    variable, 
    value, 
    temp1:humidity
    ) %>% 
  dplyr::mutate(
    variable1 = ifelse(grepl("temp",variable),"temp",variable)
    ) %>%
  ggplot(
    aes(
      x = timestamp, 
      y = value, 
      colour = variable 
      )
    )+
  geom_path(
    lwd = 0.5
    )+
  facet_wrap(
    ~variable1,
    scales = "free",
    ncol = 1)+
  theme(
    legend.position = "right"
    )+
  scale_colour_discrete(
    labels = c(
      "Internal temperature",
      "Internal temperature 2",
      "Light (relative values)",
      "Relative humidity"
      )
    )+
  xlab(
    "Timestamp"
    )

facet_labels <- c(
  expression(Light~(relative~values)),
  expression(Internal~relative~humidity~(percent)),
  expression(Internal~temperature~(~degree~C))
  
  )
  
p1 <- facet_wrap_labeller(
  p,
  facet_labels
  )


pdf("temp.pdf",width=8,height=10)
p1
dev.off()


```
